---
# tasks file for egeneralov.zabbix-agent

- name: Install zabbix-agent
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: zabbix-agent
    state: present
  register: zabbix_installation

- name: Apply agent configuration
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '{{ item.r }}.*'
    line: '{{ item.l }}'
  with_items: "{{ zbx_agent_conf }}"
  register: zabbix_conf

- name: Restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: "{% if zabbix_conf.changed or zabbix_installation.changed %}restarted{% else %}started{% endif %}"
    daemon_reload: "{% if zabbix_installation.changed %}yes{% else %}no{% endif %}"
